import { Calculator, CalendarDays, FileText, KeyRound, DollarSign, Wallet, Ruler, GraduationCap, Image as ImageIcon, Youtube, Type, Braces, Hash, Link, Palette, Tags, Clock, Share2, PenTool, TrendingUp, Compass, Percent, PiggyBank, Landmark, BookOpenCheck, CalendarClock, Bot, Heart, Sparkles, Dices, QrCode, Activity, Receipt, Coins, Smile, Flame, LineChart, Wand2, MessageSquare, Terminal, Gamepad2, ShieldAlert, Plane, BookHeart, Timer, Shuffle, AlignLeft, CheckSquare, Globe, Volume2, Coffee } from 'lucide-react';


export const toolsList = [
  {
    id: 'todo-list',
    name: 'To-Do & Notepad',
    description: 'A simple, browser-based checklist and notepad that saves your tasks automatically.',
    icon: CheckSquare,
    category: 'Education & Everyday',
    color: 'from-amber-400 to-orange-500',
    tags: ['Notes', 'Task', 'Productivity', 'Daily'],
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch & Timer',
    description: 'A simple and easy to use online stopwatch and countdown timer.',
    icon: Timer,
    category: 'Education & Everyday',
    color: 'from-blue-500 to-cyan-600',
    tags: ['Time', 'Clock', 'Countdown', 'Tracker'],
  },
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Boost productivity with the famous 25-minute work and 5-minute break technique.',
    icon: Coffee,
    category: 'Education & Everyday',
    color: 'from-rose-500 to-pink-600',
    tags: ['Timer', 'Focus', 'Productivity', 'Study'],
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert any text into natural-sounding speech. Great for reading long articles.',
    icon: Volume2,
    category: 'Education & Everyday',
    color: 'from-fuchsia-500 to-purple-600',
    tags: ['Audio', 'Speech', 'Accessibility', 'Voice'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and sentences instantly.',
    icon: FileText,
    category: 'Text & Developer Tools',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Find out your exact age in years, months, and days.',
    icon: CalendarDays,
    category: 'Education & Everyday',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create a QR code from any text or website link.',
    icon: QrCode,
    category: 'Education & Everyday',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure, random passwords.',
    icon: KeyRound,
    category: 'Text & Developer Tools',
  },
  {
    id: 'image-size-checker',
    name: 'Image Size Checker',
    description: 'Check dimensions and file size of an image.',
    icon: ImageIcon,
    category: 'Social Media & Creators',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between USD, BDT, EUR, GBP, and more.',
    icon: DollarSign,
    category: 'Finance & Math',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert common length and weight units.',
    icon: Ruler,
    category: 'Education & Everyday',
  },
  {
    id: 'ip-checker',
    name: 'My IP Address',
    description: 'Quickly check your public IPv4/IPv6 address and basic network information.',
    icon: Globe,
    category: 'Text & Developer Tools',
    color: 'from-slate-500 to-slate-700',
    tags: ['IP', 'Network', 'Internet', 'Dev'],
  },
  {
    id: 'profit-calculator',
    name: 'Profit Calculator',
    description: 'Quickly calculate net profit and ROI.',
    icon: Calculator,
    category: 'Finance & Math',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Check your Body Mass Index for tracking health.',
    icon: Activity,
    category: 'Health & Fitness',
  },
  {
    id: 'discount-calculator',
    name: 'Discount & Tax',
    description: 'Calculate final price after discount and tax.',
    icon: Percent,
    category: 'Finance & Math',
  },
  {
    id: 'youtube-title-generator',
    name: 'YouTube Title Generator',
    description: 'Generate catchy titles for your videos.',
    icon: Youtube,
    category: 'Social Media & Creators',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify or minify JSON code instantly.',
    icon: Braces,
    category: 'Text & Developer Tools',
  },
  {
    id: 'dakhil-ssc-gpa',
    name: 'Dakhil/SSC GPA (BD)',
    description: 'Calculate Dakhil/SSC Board GPA with 4th subject.',
    icon: BookOpenCheck,
    category: 'Education & Everyday',
  },
  {
    id: 'gpa-calculator',
    name: 'University GPA',
    description: 'Calculate your semester GPA easily.',
    icon: GraduationCap,
    category: 'Education & Everyday',
  },
  {
    id: 'study-routine-maker',
    name: 'Study Routine Maker',
    description: 'Generate study schedule for 2026-2028 candidates.',
    icon: CalendarClock,
    category: 'Education & Everyday',
  },
  {
    id: 'text-case-converter',
    name: 'Case Converter',
    description: 'Convert text to UPPER, lower, Title Case, etc.',
    icon: Type,
    category: 'Text & Developer Tools',
  },
  {
    id: 'base64-converter',
    name: 'Base64 Encode/Decode',
    description: 'Convert text to Base64 and vice versa safely.',
    icon: Hash,
    category: 'Text & Developer Tools',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Safely encode or decode strict URL characters.',
    icon: Link,
    category: 'Text & Developer Tools',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL.',
    icon: Palette,
    category: 'Text & Developer Tools',
  },
  {
    id: 'hashtag-generator',
    name: 'Hashtag Generator',
    description: 'Generate trending hashtags for IG, TikTok & FB.',
    icon: Tags,
    category: 'Social Media & Creators',
  },
  {
    id: 'script-timer',
    name: 'Script Timer',
    description: 'Calculate video length from your script.',
    icon: Clock,
    category: 'Social Media & Creators',
  },
  {
    id: 'social-counter',
    name: 'Social Media Counter',
    description: 'Check character limits for social platforms.',
    icon: Share2,
    category: 'Social Media & Creators',
  },
  {
    id: 'script-outline-generator',
    name: 'Script Outline',
    description: 'Generate structured video script outlines instantly.',
    icon: PenTool,
    category: 'Social Media & Creators',
  },
  {
    id: 'viral-topic-generator',
    name: 'Viral Topics',
    description: 'Find engaging and proven viral content ideas.',
    icon: TrendingUp,
    category: 'Social Media & Creators',
  },
  {
    id: 'trend-search-helper',
    name: 'Trend Finder',
    description: 'Quickly find trending content across platforms.',
    icon: Compass,
    category: 'Social Media & Creators',
  },
  {
    id: 'emi-calculator',
    name: 'EMI Calculator',
    description: 'Calculate your monthly loan EMI.',
    icon: Wallet,
    category: 'Finance & Math',
  },
  {
    id: 'compound-interest-calculator',
    name: 'Compound Interest',
    description: 'Calculate long-term investment growth.',
    icon: PiggyBank,
    category: 'Finance & Math',
  },
  {
    id: 'salary-calculator',
    name: 'Hourly to Salary',
    description: 'Convert hourly wage to annual salary.',
    icon: Landmark,
    category: 'Finance & Math',
  },
  {
    id: 'bill-splitter',
    name: 'Bill Splitter',
    description: 'Split restaurant bills and calculate tips easily.',
    icon: Receipt,
    category: 'Finance & Math',
  },
  {
    id: 'abroad-guide',
    name: 'Foreign Travel & Work Guide',
    description: 'Complete guide for working or traveling abroad. Costs, jobs, tips, and scam warnings.',
    icon: Plane,
    category: 'Education & Career',
  },
  {
    id: 'islamic-duas',
    name: 'গুরুত্বপূর্ণ দোয়া ও আমল',
    description: 'ঋণ মুক্তি, ধন-সম্পদ বৃদ্ধি, বিপদ থেকে রক্ষা এবং ভ্রমণের দোয়া (হাদিস সহ)।',
    icon: BookHeart,
    category: 'Education & Everyday',
    color: 'from-emerald-500 to-teal-600',
    tags: ['Islam', 'Dua', 'Quran', 'Hadith', 'Religion'],
  },
  {
    id: 'ai-directory',
    name: 'Top AI Tools',
    description: 'Find the best AI for writing, coding, images, and video.',
    icon: Bot,
    category: 'AI & Resources',
  },
  {
    id: 'ai-earning-guide',
    name: 'App & Website AI Earning Guide',
    description: 'Learn how to build apps or websites with AI and earn money. Full guide for PC & Phone.',
    icon: Bot,
    category: 'AI & Resources',
    color: 'from-blue-500 to-indigo-600',
    tags: ['AI', 'Guide', 'Earning', 'Web', 'App'],
  },
  {
    id: 'trading-guide',
    name: 'Trading Guide',
    description: 'Learn strategies for Forex, Crypto, and Binary markets.',
    icon: LineChart,
    category: 'Finance & Math',
  },
  {
    id: 'random-number',
    name: 'Random Number Generator',
    description: 'Generate arbitrary numbers based on your custom range and parameters.',
    icon: Shuffle,
    category: 'Finance & Math',
    color: 'from-purple-500 to-indigo-600',
    tags: ['Math', 'Random', 'Generator', 'Utility'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate customizable dummy text for your design and development projects.',
    icon: AlignLeft,
    category: 'Text & Developer Tools',
    color: 'from-orange-500 to-red-600',
    tags: ['Text', 'Design', 'Development', 'Placeholder'],
  },
  {
    id: 'fake-tweet',
    name: 'Fake Tweet Generator',
    description: 'Create realistic fake tweets for pranks and memes.',
    icon: MessageSquare,
    category: 'Fun & Games',
  },
  {
    id: 'fancy-text',
    name: 'Fancy Text Generator',
    description: 'Convert normal text to stylish fonts for social media.',
    icon: Wand2,
    category: 'Fun & Games',
  },
  {
    id: 'love-calculator',
    name: 'Love Calculator',
    description: 'Calculate the love percentage between two names.',
    icon: Heart,
    category: 'Fun & Games',
  },
  {
    id: 'zodiac-finder',
    name: 'Zodiac Finder',
    description: 'Find your zodiac sign from your birth date.',
    icon: Sparkles,
    category: 'Fun & Games',
  },
  {
    id: 'magic-8-ball',
    name: 'Magic 8 Ball',
    description: 'Ask a yes or no question and get a magical answer.',
    icon: Dices,
    category: 'Fun & Games',
  },
  {
    id: 'coin-flipper',
    name: 'Coin Flipper',
    description: 'Flip a virtual coin for quick decisions.',
    icon: Coins,
    category: 'Fun & Games',
  },
  {
    id: 'truth-or-dare',
    name: 'Truth or Dare',
    description: 'Generate fun truth or dare questions for friends.',
    icon: Flame,
    category: 'Fun & Games',
  },
  {
    id: 'joke-generator',
    name: 'Joke Generator',
    description: 'Get a random customized programming or dad joke.',
    icon: Smile,
    category: 'Fun & Games',
  },
];
